name: build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    strategy:
        matrix:
          go-version: [1.15.x]
          os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - 
        uses: actions/checkout@master
        with:
            fetch-depth: 1
      -
        name: Set Username/Repo as ENV vars
        run: echo "USER_REPO"=$(echo "$GITHUB_REPOSITORY" | awk '{print tolower($1)}' | sed -e "s/:refs//") >> $GITHUB_ENV
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Local docker multi-arch build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: false
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            VERSION=latest-dev
            GIT_COMMIT=${{ github.sha }}
            REPO_URL=https://github.com/${{ env.USER_REPO }}
          tags: ghcr.io/making/inlets:${{ github.sha }}
